"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import { ArrowRight, CheckCircle2, Zap, Shield, BarChart3, Database } from "lucide-react";

export default function LandingPage() {
  return (
    <div className="flex flex-col min-h-screen">
      {/* Hero Section */}
      <section className="relative pt-32 pb-20 lg:pt-48 lg:pb-32 overflow-hidden">
        <div className="absolute inset-0 -z-10 bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-[#7C3AED]/20 via-[#0A0A0A] to-[#0A0A0A]"></div>
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <motion.h1 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            className="text-5xl md:text-7xl font-extrabold tracking-tight text-white mb-8"
          >
            AI-Powered Backend <br className="hidden md:block" />
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-[#7C3AED] to-[#06B6D4]">
              Performance Diagnostics
            </span>
          </motion.h1>
          <motion.p 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.1 }}
            className="mt-4 text-xl text-[#A1A1AA] max-w-3xl mx-auto mb-10"
          >
            Automatically detect slow APIs, memory leaks, CPU spikes, and inefficient database queries. Get AI-driven recommendations to optimize your backend instantly.
          </motion.p>
          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.2 }}
            className="flex flex-col sm:flex-row justify-center gap-4"
          >
            <Link
              href="/dashboard"
              className="inline-flex items-center justify-center rounded-full bg-white px-8 py-3.5 text-sm font-semibold text-black shadow-sm hover:bg-gray-200 transition-colors"
            >
              Start Analysis <ArrowRight className="ml-2 h-4 w-4" />
            </Link>
            <Link
              href="#demo"
              className="inline-flex items-center justify-center rounded-full border border-[#222222] bg-[#111111] px-8 py-3.5 text-sm font-semibold text-white shadow-sm hover:bg-[#222222] transition-colors"
            >
              View Demo
            </Link>
          </motion.div>
        </div>
      </section>

      {/* Trusted Tech */}
      <section className="py-10 border-y border-[#222222] bg-[#111111]/50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <p className="text-sm font-semibold text-[#A1A1AA] tracking-wide uppercase mb-6">Works with your favorite technologies</p>
          <div className="flex justify-center gap-8 md:gap-16 flex-wrap opacity-70">
            <div className="flex items-center gap-2 text-xl font-bold"><Database className="h-6 w-6"/> Node.js</div>
            <div className="flex items-center gap-2 text-xl font-bold"><Database className="h-6 w-6"/> Express</div>
            <div className="flex items-center gap-2 text-xl font-bold"><Database className="h-6 w-6"/> MongoDB</div>
            <div className="flex items-center gap-2 text-xl font-bold"><Database className="h-6 w-6"/> PostgreSQL</div>
            <div className="flex items-center gap-2 text-xl font-bold"><Database className="h-6 w-6"/> Redis</div>
          </div>
        </div>
      </section>

      {/* Features */}
      <section id="features" className="py-24">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold tracking-tight text-white sm:text-4xl">Everything you need to scale</h2>
            <p className="mt-4 text-lg text-[#A1A1AA]">Identify bottlenecks before they impact your users.</p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {[
              { icon: Zap, title: "Instant Diagnostics", desc: "Scan your logs and metrics to find N+1 queries, memory leaks, and CPU blocks." },
              { icon: Shield, title: "AI Recommendations", desc: "Get actionable code snippets and configuration fixes generated by our AI engine." },
              { icon: BarChart3, title: "Historical Trends", desc: "Track your performance score over time and measure the impact of optimizations." }
            ].map((feature, i) => (
              <motion.div 
                key={i}
                whileHover={{ y: -5 }}
                className="p-8 rounded-2xl bg-[#111111] border border-[#222222] hover:border-[#7C3AED]/50 transition-colors"
              >
                <div className="h-12 w-12 rounded-lg bg-[#7C3AED]/10 flex items-center justify-center mb-6">
                  <feature.icon className="h-6 w-6 text-[#7C3AED]" />
                </div>
                <h3 className="text-xl font-semibold text-white mb-3">{feature.title}</h3>
                <p className="text-[#A1A1AA]">{feature.desc}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>
      
      {/* Footer */}
      <footer className="border-t border-[#222222] py-12 mt-auto">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex flex-col md:flex-row justify-between items-center">
          <div className="flex items-center gap-2 mb-4 md:mb-0">
            <Zap className="h-6 w-6 text-[#7C3AED]" />
            <span className="text-lg font-bold text-white">PerfDoctor AI</span>
          </div>
          <p className="text-sm text-[#A1A1AA]">© 2026 PerfDoctor AI. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
}
